export const ALL_PRODUCTS = [
  {
    id: 1,
    brand: "Adidas",
    name: "Cartoon Astronaut T-shirts",
    price: 1999,
    img: "/img/products/f1.jpg",
    category: "featured",
  },
  {
    id: 2,
    brand: "Zara",
    name: "Leaves T-shirts",
    price: 1000,
    img: "/img/products/f2.jpg",
    category: "featured",
  },
  {
    id: 3,
    brand: "Nike",
    name: "Colorful T-shirts",
    price: 1500,
    img: "/img/products/f3.jpg",
    category: "featured",
  },
  {
    id: 4,
    brand: "Puma",
    name: "White T-shirts",
    price: 999,
    img: "/img/products/f4.jpg",
    category: "featured",
  },
  {
    id: 5,
    brand: "Adidas",
    name: "Flower T-shirts",
    price: 555,
    img: "/img/products/f5.jpg",
    category: "featured",
  },
  {
    id: 6,
    brand: "Puma",
    name: "Orange Blue T-shirts",
    price: 299,
    img: "/img/products/f6.jpg",
    category: "featured",
  },
  {
    id: 7,
    brand: "Zara",
    name: "Plain Lower",
    price: 599,
    img: "/img/products/f7.jpg",
    category: "featured",
  },
  {
    id: 8,
    brand: "Nike",
    name: "Latest Design Top",
    price: 2999,
    img: "/img/products/f8.jpg",
    category: "featured",
  },
  {
    id: 9,
    brand: "Adidas",
    name: "Light Blue Shirt",
    price: 1999,
    img: "/img/products/n1.jpg",
    category: "new-arrival",
  },
  {
    id: 10,
    brand: "Zara",
    name: "Purple Shirt",
    price: 1000,
    img: "/img/products/n2.jpg",
    category: "new-arrival",
  },
  {
    id: 11,
    brand: "Nike",
    name: "White Shirt",
    price: 1500,
    img: "/img/products/n3.jpg",
    category: "new-arrival",
  },
  {
    id: 12,
    brand: "Puma",
    name: "T-shirts",
    price: 999,
    img: "/img/products/n4.jpg",
    category: "new-arrival",
  },
  {
    id: 13,
    brand: "Adidas",
    name: "Blue Plane Shirt",
    price: 555,
    img: "/img/products/n5.jpg",
    category: "new-arrival",
  },
  {
    id: 14,
    brand: "Puma",
    name: "Half Pant",
    price: 299,
    img: "/img/products/n6.jpg",
    category: "new-arrival",
  },
  {
    id: 15,
    brand: "Zara",
    name: "Brown Shirt",
    price: 599,
    img: "/img/products/n7.jpg",
    category: "new-arrival",
  },
  {
    id: 16,
    brand: "Nike",
    name: "Latest Black T-shirts",
    price: 2999,
    img: "/img/products/n8.jpg",
    category: "new-arrival",
  },
  {
    id: 17,
    brand: "Nike",
    name: "Gray Super Top",
    price: 2000,
    img: "/img/products/grey.png",
    category: "new-arrival",
  },
  {
    id: 18,
    brand: "Zara",
    name: "White Plane T-shirts",
    price: 1999,
    img: "/img/products/white.png",
    category: "featured",
  },
  {
    id: 19,
    brand: "Puma",
    name: "Female Light Blue T-shirts",
    price: 799,
    img: "/img/products/bl.png",
    category: "normal",
  },
];
